config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'collections/index'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :collections, shallow: true do
    resources :items, shallow: true do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
  end

  get 'items/:item_id/comments.:id', to: 'comments#destroy'

  get 'collections-all', to: 'collections#all_collections', as: :all_collections

  get '%23.:id', to: 'collections#destroy', as: :delete_collection

  get '%2523.:id', to: 'items#destroy', as: :delete_item

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/block_user/:id', to: 'admin#block_user', as: :block_user
  get 'admin/unblock_user/:id', to: 'admin#unblock_user', as: :unblock_user
  get 'admin/delete_user/:id', to: 'admin#delete_user', as: :delete_user
  get 'admin/add_admin/:id', to: 'admin#add_admin', as: :add_admin
  get 'admin/remove_admin/:id', to: 'admin#remove_admin', as: :remove_admin

  get 'toggle_language', to: 'application#toggle_language'
  post 'toggle_theme', to: 'application#toggle_theme'
  patch 'batch_action_admin', to: 'admin#batch_action'

  get 'search', to: 'search#index'

  resources :tickets, only: [:new, :create, :index]
  resource :profile, only: [:show], controller: 'profiles' do
    post :regenerate_api_token, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :collections, only: [:index]
    end
  end

  root to: 'home#index'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query].present?
      @resultcollection = Collection.search(params[:query])
      @resultitem = Item.search(params[:query])
    else
      @resultcollection = Collection.none
      @resultitem = Item.none
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div class="container my-3">
  <h1 class="text-center my-3"><%= t('search.results') %></h1>

  <% if @resultitem.present? or @resultcollection.present? %>
    <div class="row">
      <% @resultitem.each do |item| %>
        <div class="col-md-4 mb-4">
          <div class="card h-100 d-flex flex-column">
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= t('search.itemname') %>: <%= link_to item.name, item_path(item) %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= t('search.itemid') %>: <%= link_to item.id, item_path(item) %></h6>
              <p class="card-text"><%= t('search.tags') %>: <%= item.tag %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row">
      <% @resultcollection.each do |collection| %>
        <div class="col-md-4 mb-4">
          <div class="card h-100 d-flex flex-column">
            <% if collection.image_url.present? %>
              <img src="<%= collection.image_url %>" alt="<%= collection.name %>" class="img-fluid" style="max-height: 300px; object-fit: contain;">
            <% else %>
              <img src="https://i.ibb.co/vq6Bc4g/placeholder.jpg" alt="Placeholder Image" class="img-fluid" style="max-height: 300px; object-fit: contain;">
            <% end %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= t('search.collectionname') %>: <%= link_to collection.name, collection_path(collection) %></h5>
              <h6 class="card-subtitle mb-2 text-muted"><%= t('search.collectionid') %>: <%= link_to collection.id, collection_path(collection) %></h6>
              <p class="card-text"><%= t('search.collectioncategory') %>: <%= collection.category %></p>
              <p class="card-text"><%= t('search.collectiondescription') %>: <%= collection.description %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <hr>
    <h3 class="text-center"><%= t('search.nothing') %>.</h3>
  <% end %>
</div>