config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'collections/index'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :collections, shallow: true do
    resources :items, shallow: true do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
  end

  get 'items/:item_id/comments.:id', to: 'comments#destroy'

  get 'collections-all', to: 'collections#all_collections', as: :all_collections

  get '%23.:id', to: 'collections#destroy', as: :delete_collection

  get '%2523.:id', to: 'items#destroy', as: :delete_item

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/block_user/:id', to: 'admin#block_user', as: :block_user
  get 'admin/unblock_user/:id', to: 'admin#unblock_user', as: :unblock_user
  get 'admin/delete_user/:id', to: 'admin#delete_user', as: :delete_user
  get 'admin/add_admin/:id', to: 'admin#add_admin', as: :add_admin
  get 'admin/remove_admin/:id', to: 'admin#remove_admin', as: :remove_admin

  get 'toggle_language', to: 'application#toggle_language'
  post 'toggle_theme', to: 'application#toggle_theme'
  patch 'batch_action_admin', to: 'admin#batch_action'

  get 'search', to: 'search#index'

  resources :tickets, only: [:new, :create, :index]
  resource :profile, only: [:show], controller: 'profiles' do
    post :regenerate_api_token, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :collections, only: [:index]
    end
  end

  root to: 'home#index'
end

app/models/item.rb
class Item < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: [:name, :custom_string1_value, :custom_string2_value, :custom_string3_value, 
                                            :custom_text1_value, :custom_text2_value, :custom_text3_value, :tag],
                           associated_against: {
                             comments: [:body]
                           },
                           using: {
                             tsearch: { prefix: true }
                           }

  belongs_to :collection
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_by_users, through: :likes, source: :user

  validates :name, presence: true

  def liked_by?(user)
    likes.exists?(user: user)
  end

  def custom_field_values
    values = {}
    (1..3).each do |i|
      values["custom_string#{i}_value"] = send("custom_string#{i}_value") if collection.send("custom_string#{i}_state")
      values["custom_int#{i}_value"] = send("custom_int#{i}_value") if collection.send("custom_int#{i}_state")
      values["custom_text#{i}_value"] = send("custom_text#{i}_value") if collection.send("custom_text#{i}_state")
      values["custom_bool#{i}_value"] = send("custom_bool#{i}_value") if collection.send("custom_bool#{i}_state")
      values["custom_date#{i}_value"] = send("custom_date#{i}_value") if collection.send("custom_date#{i}_state")
    end
    values
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :authenticate_admin!, except: [:show, :edit, :update, :new, :create, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_collection, only: [:index, :new, :create]

  def index
    @items = @collection.items
  end

  def show
    @collection = @item.collection
    @user = @collection.user
    @comments = @item.comments
    @comment = Comment.new
  end

  def new
    @item = @collection.items.build
  end

  def create
    if @collection.user == current_user or current_user.admin?
      @item = @collection.items.build(item_params)
      @item.tag = params[:tag].split(',').map(&:strip) if params[:tag]
      if @item.save
        redirect_to collection_path(@collection), notice: 'Item was successfully created.'
      else
        render :new
      end
    end
  end

  def edit
    @collection = @item.collection
  end

  def update
    if @item.collection.user == current_user or current_user.admin?
      @item.tag = params[:tag].split(',').map(&:strip) if params[:tag]
      if @item.update(item_params)
        redirect_to item_path, notice: 'Item was successfully updated.'
      else
        render :edit
      end
    end
  end

  def destroy
    if @item.collection.user == current_user or current_user.admin?
      @item.destroy
      redirect_to collection_path(@item.collection), notice: 'Item was successfully destroyed.'
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :custom_string1_value, :custom_string2_value, :custom_string3_value,
                                 :custom_int1_value, :custom_int2_value, :custom_int3_value, :custom_text1_value,
                                 :custom_text2_value, :custom_text3_value, :custom_bool1_value, :custom_bool2_value,
                                 :custom_bool3_value, :custom_date1_value, :custom_date2_value, :custom_date3_value, :tag)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="container mt-3">
  <h1 class="mb-4"><%= t('edititem.title') %>: <%= @item.id %></h1>

  <%= form_with(model: @item, local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
        <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, t('edititem.name'), class: "form-label" %>
      <%= form.text_field :name, class: "form-control", value: @item.name %>
    </div>

    <div class="mb-3">
      <%= form.label :tags, t('edititem.tags'), class: "form-label" %>
      <%= text_field_tag :tag, @item.tag, class: "form-control", placeholder: t('edititem.tagplaceholder'), list: "tag-suggestions" %>
      <datalist id='tag-suggestions'>
        <% Item.pluck(:tag).join(',').split(',').uniq.each do |tag|%>
          <option value=<%=tag%>></option>
        <%end%>
      </datalist>
    </div>

    <% if @collection.custom_string1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_string1_name, class: "form-label" %>
        <%= form.text_field :custom_string1_value, class: "form-control", value: @item.custom_string1_value %>
      </div>
    <% end %>
    <% if @collection.custom_string2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_string2_name, class: "form-label" %>
        <%= form.text_field :custom_string2_value, class: "form-control", value: @item.custom_string2_value %>
      </div>
    <% end %>
    <% if @collection.custom_string3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_string3_name, class: "form-label" %>
        <%= form.text_field :custom_string3_value, class: "form-control", value: @item.custom_string3_value %>
      </div>
    <% end %>

    <% if @collection.custom_int1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_int1_name, class: "form-label" %>
        <%= form.number_field :custom_int1_value, class: "form-control", value: @item.custom_int1_value %>
      </div>
    <% end %>
    <% if @collection.custom_int2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_int2_name, class: "form-label" %>
        <%= form.number_field :custom_int2_value, class: "form-control", value: @item.custom_int2_value %>
      </div>
    <% end %>
    <% if @collection.custom_int3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_int3_name, class: "form-label" %>
        <%= form.number_field :custom_int3_value, class: "form-control", value: @item.custom_int3_value %>
      </div>
    <% end %>

    <% if @collection.custom_text1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_text1_name, class: "form-label" %>
        <%= form.text_area :custom_text1_value, class: "form-control", rows: 3, value: @item.custom_text1_value %>
      </div>
    <% end %>
    <% if @collection.custom_text2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_text2_name, class: "form-label" %>
        <%= form.text_area :custom_text2_value, class: "form-control", rows: 3, value: @item.custom_text2_value %>
      </div>
    <% end %>
    <% if @collection.custom_text3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_text3_name, class: "form-label" %>
        <%= form.text_area :custom_text3_value, class: "form-control", rows: 3, value: @item.custom_text3_value %>
      </div>
    <% end %>

    <% if @collection.custom_bool1_state %>
      <div class="mb-3 form-check">
        <%= form.check_box :custom_bool1_value, { class: "form-check-input", checked: @item.custom_bool1_value } %>
        <%= form.label @collection.custom_bool1_name, class: "form-check-label" %>
      </div>
    <% end %>
    <% if @collection.custom_bool2_state %>
      <div class="mb-3 form-check">
        <%= form.check_box :custom_bool2_value, { class: "form-check-input", checked: @item.custom_bool2_value } %>
        <%= form.label @collection.custom_bool2_name, class: "form-check-label" %>
      </div>
    <% end %>
    <% if @collection.custom_bool3_state %>
      <div class="mb-3 form-check">
        <%= form.check_box :custom_bool3_value, { class: "form-check-input", checked: @item.custom_bool3_value } %>
        <%= form.label @collection.custom_bool3_name, class: "form-check-label" %>
      </div>
    <% end %>

    <% if @collection.custom_date1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_date1_name, class: "form-label" %>
        <%= form.date_field :custom_date1_value, class: "form-control", value: @item.custom_date1_value %>
      </div>
    <% end %>
    <% if @collection.custom_date2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_date2_name, class: "form-label" %>
        <%= form.date_field :custom_date2_value, class: "form-control", value: @item.custom_date2_value %>
      </div>
    <% end %>
    <% if @collection.custom_date3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_date3_name, class: "form-label" %>
        <%= form.date_field :custom_date3_value, class: "form-control", value: @item.custom_date3_value %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.submit t('edititem.update'), class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to t('edititem.back'), collection_path(@collection), class: "btn btn-secondary mt-3" %>
</div>

app/views/items/new.html.erb
<div class="container mt-3">
  <h1 class="mb-4"><%= t('newitem.title') %></h1>

  <%= form_with(model: [@collection, @item], local: true, html: { class: 'needs-validation', novalidate: true }) do |form| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
        <ul>
          <% @item.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.label :name, t('newitem.name'), class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :tags, t('newitem.tags'), class: "form-label" %>
      <%= text_field_tag :tag, @item.tag, class: "form-control", placeholder: t('newitem.tagplaceholder'), list: "tag-suggestions" %>
      <datalist id='tag-suggestions'>
        <% Item.pluck(:tag).join(',').split(',').uniq.each do |tag|%>
          <option value=<%=tag%>></option>
        <%end%>
      </datalist>
    </div>

    <% if @collection.custom_string1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_string1_name, class: "form-label" %>
        <%= form.text_field :custom_string1_value, class: "form-control" %>
      </div>
    <% end %>
    <% if @collection.custom_string2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_string2_name, class: "form-label" %>
        <%= form.text_field :custom_string2_value, class: "form-control" %>
      </div>
    <% end %>
    <% if @collection.custom_string3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_string3_name, class: "form-label" %>
        <%= form.text_field :custom_string3_value, class: "form-control" %>
      </div>
    <% end %>

    <% if @collection.custom_int1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_int1_name, class: "form-label" %>
        <%= form.number_field :custom_int1_value, class: "form-control" %>
      </div>
    <% end %>
    <% if @collection.custom_int2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_int2_name, class: "form-label" %>
        <%= form.number_field :custom_int2_value, class: "form-control" %>
      </div>
    <% end %>
    <% if @collection.custom_int3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_int3_name, class: "form-label" %>
        <%= form.number_field :custom_int3_value, class: "form-control" %>
      </div>
    <% end %>

    <% if @collection.custom_text1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_text1_name, class: "form-label" %>
        <%= form.text_area :custom_text1_value, class: "form-control", rows: 3 %>
      </div>
    <% end %>
    <% if @collection.custom_text2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_text2_name, class: "form-label" %>
        <%= form.text_area :custom_text2_value, class: "form-control", rows: 3 %>
      </div>
    <% end %>
    <% if @collection.custom_text3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_text3_name, class: "form-label" %>
        <%= form.text_area :custom_text3_value, class: "form-control", rows: 3 %>
      </div>
    <% end %>

    <% if @collection.custom_bool1_state %>
      <div class="mb-3 form-check">
        <%= form.check_box :custom_bool1_value, class: "form-check-input" %>
        <%= form.label @collection.custom_bool1_name, class: "form-check-label" %>
      </div>
    <% end %>
    <% if @collection.custom_bool2_state %>
      <div class="mb-3 form-check">
        <%= form.check_box :custom_bool2_value, class: "form-check-input" %>
        <%= form.label @collection.custom_bool2_name, class: "form-check-label" %>
      </div>
    <% end %>
    <% if @collection.custom_bool3_state %>
      <div class="mb-3 form-check">
        <%= form.check_box :custom_bool3_value, class: "form-check-input" %>
        <%= form.label @collection.custom_bool3_name, class: "form-check-label" %>
      </div>
    <% end %>

    <% if @collection.custom_date1_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_date1_name, class: "form-label" %>
        <%= form.date_field :custom_date1_value, class: "form-control" %>
      </div>
    <% end %>
    <% if @collection.custom_date2_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_date2_name, class: "form-label" %>
        <%= form.date_field :custom_date2_value, class: "form-control" %>
      </div>
    <% end %>
    <% if @collection.custom_date3_state %>
      <div class="mb-3">
        <%= form.label @collection.custom_date3_name, class: "form-label" %>
        <%= form.date_field :custom_date3_value, class: "form-control" %>
      </div>
    <% end %>

    <div class="mb-3">
      <%= form.submit  t('newitem.create'), class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to t('newitem.back'), collection_path(@collection), class: "btn btn-secondary mt-3" %>
</div>

app/views/items/show.html.erb
<div class="container mt-3">
  <div class="row mb-4">
    <div class="col">
      <h1><%= t('showitem.name') %>: <%= @item.name %></h1>
      <h3><%= t('showitem.id') %>: <%= @item.id %></h3>
      <h6><%= t('showitem.collectionid') %>: <%= @collection.id %>, <%= t('showitem.collectionname') %>: <%= @collection.name %></h6>
      <h6><%= t('showitem.userid') %>: <%= @user.id %>, <%= t('showitem.username') %>: <%= @user.name %></h6>
      <p><strong><%= t('showitem.tags') %>:</strong> <%= @item.tag %></p>
      <ul class="list-group">
        <% if @collection.custom_string1_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_string1_name %>:</strong> <%= @item.custom_string1_value %>
          </li>
        <% end %>
        <% if @collection.custom_string2_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_string2_name %>:</strong> <%= @item.custom_string2_value %>
          </li>
        <% end %>
        <% if @collection.custom_string3_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_string3_name %>:</strong> <%= @item.custom_string3_value %>
          </li>
        <% end %>

        <% if @collection.custom_int1_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_int1_name %>:</strong> <%= @item.custom_int1_value %>
          </li>
        <% end %>
        <% if @collection.custom_int2_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_int2_name %>:</strong> <%= @item.custom_int2_value %>
          </li>
        <% end %>
        <% if @collection.custom_int3_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_int3_name %>:</strong> <%= @item.custom_int3_value %>
          </li>
        <% end %>

        <% if @collection.custom_text1_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_text1_name %>:</strong> <%= @item.custom_text1_value %>
          </li>
        <% end %>
        <% if @collection.custom_text2_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_text2_name %>:</strong> <%= @item.custom_text2_value %>
          </li>
        <% end %>
        <% if @collection.custom_text3_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_text3_name %>:</strong> <%= @item.custom_text3_value %>
          </li>
        <% end %>

        <% if @collection.custom_bool1_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_bool1_name %>:</strong> <%= @item.custom_bool1_value ? t('showcollection.yess') : t('showcollection.noo')%>
          </li>
        <% end %>
        <% if @collection.custom_bool2_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_bool2_name %>:</strong> <%= @item.custom_bool2_value ? t('showcollection.yess') : t('showcollection.noo')%>
          </li>
        <% end %>
        <% if @collection.custom_bool3_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_bool3_name %>:</strong> <%= @item.custom_bool3_value ? t('showcollection.yess') : t('showcollection.noo')%>
          </li>
        <% end %>

        <% if @collection.custom_date1_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_date1_name %>:</strong> <%= @item.custom_date1_value %>
          </li>
        <% end %>
        <% if @collection.custom_date2_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_date2_name %>:</strong> <%= @item.custom_date2_value %>
          </li>
        <% end %>
        <% if @collection.custom_date3_state %>
          <li class="list-group-item">
            <strong><%= @collection.custom_date3_name %>:</strong> <%= @item.custom_date3_value %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col">
        <div class="d-flex align-items-center">
          <% if user_signed_in? %>
            <% if current_user and @item.likes.exists?(user: current_user) %>
              <%= button_to t('showitem.unlike'),item_like_path(@item), method: :delete, remote: true, class: 'btn btn-outline-danger like-button me-3'%>
            <% else %>
              <%= button_to t('showitem.like'), item_like_path(@item), method: :post, remote: true, class: 'btn btn-outline-primary like-button me-3'%>
            <% end %>
          <% end %>
          <p class="mb-0 like-count ml-2 text-primary"><strong><%= t('showitem.likes') %>:</strong> <%= @item.likes.count %></p>
        </div>
      </div>
    </div>

    <div class="row mb-4">
      <div class="col">
        <h2><i class="far fa-comments me-2"></i><%= t('showitem.comments') %></h2>
        <div id="comments" class="list-group" data-item-id="<%= @item.id %>">
          <% @item.comments.each do |comment| %>
            <div class="list-group-item" id="comment-<%= comment.id %>">
              <p><strong><%= t('showitem.userid') %>: <%= comment.user.id %>, <%= t('showitem.username') %>: <%= comment.user.name %> | </strong> <%= comment.body %></p>
              <% if user_signed_in? %>
                <% if @item.collection.user == current_user or comment.user == current_user or current_user.admin? %>
                  <%= link_to t('showitem.deletecomment'), item_comments_path(comment.item, comment), method: :delete, remote: true, class: 'btn btn-outline-danger btn-sm' %>
                <% end %>
              <% end %>
            </div>
          <% end %>
      </div>
    </div>
  </div>

  <div class="row mb-4">
    <div class="col">
      <% if user_signed_in? %>
        <%= form_with(model: [@item, @item.comments.build], remote: true, id: "comment-form") do |form| %>
          <div class="form-group">
            <%= form.label :body, t('showitem.addcomment') %>
            <%= form.text_area :body, class: "form-control", rows: 3 %>
          </div>
          <div class="form-group">
            <%= form.submit t('showitem.entercomment'), class: "btn btn-primary btn-sm mt-2" %>
          </div>
        <% end %>
      <% else %>
        <p><%= t('showitem.youmustbe') %> <%= link_to t('showitem.loggedin'), new_user_session_path %> <%= t('showitem.toaddacomment') %>.</p>
      <% end %>
    </div>
  </div>  
</div>