config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      get 'collections/index'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :collections, shallow: true do
    resources :items, shallow: true do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
  end

  get 'items/:item_id/comments.:id', to: 'comments#destroy'

  get 'collections-all', to: 'collections#all_collections', as: :all_collections

  get '%23.:id', to: 'collections#destroy', as: :delete_collection

  get '%2523.:id', to: 'items#destroy', as: :delete_item

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end

  get 'admin', to: 'admin#index', as: :admin
  get 'admin/block_user/:id', to: 'admin#block_user', as: :block_user
  get 'admin/unblock_user/:id', to: 'admin#unblock_user', as: :unblock_user
  get 'admin/delete_user/:id', to: 'admin#delete_user', as: :delete_user
  get 'admin/add_admin/:id', to: 'admin#add_admin', as: :add_admin
  get 'admin/remove_admin/:id', to: 'admin#remove_admin', as: :remove_admin

  get 'toggle_language', to: 'application#toggle_language'
  post 'toggle_theme', to: 'application#toggle_theme'
  patch 'batch_action_admin', to: 'admin#batch_action'

  get 'search', to: 'search#index'

  resources :tickets, only: [:new, :create, :index]
  resource :profile, only: [:show], controller: 'profiles' do
    post :regenerate_api_token, on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :collections, only: [:index]
    end
  end

  root to: 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head>
  <title><%= t('site.title') %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <style>
    body {
      padding-top: 99px;
    }
  </style>
</head>
<body data-bs-theme="<%= @theme %>">
  <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
    <div class="container">
      <a class="navbar-brand me-5 mt-2 mb-2" href="/"><%= t('site.title') %></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar01" aria-controls="navbar01" aria-expanded="false" aria-label="Toggle navigation" id="navbar-toggler">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to t('nav.all_collections'), all_collections_path, class: 'nav-link mt-2 mb-2' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to t('nav.my_profile'), profile_path, class: 'nav-link mt-2 mb-2' %>
            </li>  
            <li class="nav-item">
              <%= link_to t('nav.my_collections'), collections_path(current_user), class: 'nav-link mt-2 mb-2' %>
            </li>
            <% if current_user.admin? %>
              <li class="nav-item">
                <%= link_to t('nav.admin_page'), admin_path, class: 'nav-link mt-2 mb-2' %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to t('nav.logout'), destroy_user_session_path, method: :delete, class: 'nav-link mt-2 mb-2' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to t('nav.login'), new_user_session_path, class: 'nav-link mt-2 mb-2' %>
            </li>
            <li class="nav-item">
              <%= link_to t('nav.register'), new_user_registration_path, class: 'nav-link mt-2 mb-2' %>
            </li>
          <% end %>
        </ul>
        <%= form_with url: search_path, method: :get, local: true do %>
          <%= text_field_tag :query, params[:query], placeholder: t('nav.search'), class: "form-control me-2 mt-2 mb-2", list: "tag-suggestions" %>
          <%= submit_tag t('nav.search'), class: "btn btn-success d-lg-none mt-2 mb-2" %>
          <datalist id='tag-suggestions'>
            <% Item.pluck(:tag).join(',').split(',').uniq.each do |tag|%>
              <option value=<%=tag%>></option>
            <%end%>
          </datalist>
        <% end %>

        <div class="d-flex align-items-center ms-2">
          <%= form_with url: toggle_theme_path, method: :post, local: true do %>
            <button type="submit" class="btn btn-outline-dark me-2 mt-2 mb-2">
              <% if @theme == 'dark' %>
                <i class="far fa-lightbulb"></i>
              <% else %>
                <i class="fas fa-lightbulb"></i>
              <% end %>
            </button>
          <% end %>
          <%= link_to t('nav.switch_language'), toggle_language_path, method: :post, class: 'btn btn-outline-light mt-2 mb-2' %>
        </div>
      </div>
    </div>
  </nav>
  
  <div class="container mb-5 pb-5">
    <%= yield %>
  </div>

  <% if user_signed_in? %>
    <div class="container d-flex justify-content-end my-5 py-5">
      <%= link_to new_ticket_path, class: 'btn btn-warning' do %>
        <i class="fas fa-ticket-alt me-2"></i>  <%= t('profile.createticket') %>
      <% end %>
    </div>
  <% end %>

  <div class="mt-5 pt-5">
    <hr>
  </div>
 
  <footer>
    <h6 class="text-center py-5"><%= t('footer.text') %></h6>
  </footer>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var navbarToggler = document.getElementById('navbar-toggler');
      var navbarCollapse = document.getElementById('navbar01');
  
      navbarToggler.addEventListener('click', function() {
        navbarCollapse.classList.toggle('show');
      });
    });
  </script>
</body>
</html>